# Movie preprocessing

In [3]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [4]:
import pandas as pd
import numpy as np
from src import preprocess as prep

In [5]:
vid = prep.process_video("00001")

'00001'

(127, 270, 480, 3)
[[[[  0   0   0]
   [  0   0   0]
   [  0   0   0]
   ...
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]]

  [[  0   0   0]
   [  0   0   0]
   [  0   0   0]
   ...
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]]

  [[  0   0   0]
   [  0   0   0]
   [  0   0   0]
   ...
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]]

  ...

  [[  0   0   0]
   [  0   0   0]
   [  0   0   0]
   ...
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]]

  [[  0   0   0]
   [  0   0   0]
   [  0   0   0]
   ...
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]]

  [[  0   0   0]
   [  0   0   0]
   [  0   0   0]
   ...
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]]]


 [[[  0   0   0]
   [  0   0   0]
   [  0   0   0]
   ...
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]]

  [[  0   0   0]
   [  0   0   0]
   [  0   0   0]
   ...
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]]

  [[  0   0   0]
   [  0   0   0]
   [  0   0   0]
   ...
   [  0   0   0]
   [  0  

(12, 270, 480, 3)
[[[[ 95  92 143]
   [ 92  89 140]
   [ 91  87 140]
   ...
   [ 77  69 105]
   [ 77  69 105]
   [ 77  69 105]]

  [[ 94  91 142]
   [ 90  87 138]
   [ 90  86 139]
   ...
   [ 77  69 105]
   [ 76  68 104]
   [ 78  70 106]]

  [[ 91  88 139]
   [ 88  85 136]
   [ 85  81 134]
   ...
   [ 76  68 104]
   [ 77  69 105]
   [ 78  70 106]]

  ...

  [[ 93  92 127]
   [ 89  88 123]
   [ 87  86 121]
   ...
   [107 119 138]
   [102 115 136]
   [ 99 112 133]]

  [[ 96  95 130]
   [ 91  90 125]
   [ 90  89 124]
   ...
   [107 119 138]
   [102 115 136]
   [100 113 134]]

  [[ 97  96 131]
   [ 93  92 127]
   [ 91  90 125]
   ...
   [108 120 139]
   [104 117 138]
   [102 115 136]]]


 [[[108 104 149]
   [106 102 147]
   [103  99 144]
   ...
   [ 90  84 108]
   [ 87  81 105]
   [ 88  82 106]]

  [[106 102 147]
   [104 100 145]
   [101  97 142]
   ...
   [ 90  84 108]
   [ 86  80 104]
   [ 90  84 108]]

  [[106 102 147]
   [105 101 146]
   [100  96 141]
   ...
   [ 88  82 108]
   [ 87  8

(58, 270, 480, 3)
[[[[ 91  76  79]
   [ 73  58  61]
   [ 93  78  81]
   ...
   [ 39  50  58]
   [ 35  46  54]
   [ 33  44  52]]

  [[ 92  77  80]
   [ 73  58  61]
   [ 93  78  81]
   ...
   [ 39  50  58]
   [ 37  48  56]
   [ 34  45  53]]

  [[ 94  79  82]
   [ 71  56  59]
   [ 90  75  78]
   ...
   [ 44  52  61]
   [ 41  49  58]
   [ 40  48  57]]

  ...

  [[168 154 147]
   [171 157 150]
   [173 159 152]
   ...
   [150 137 133]
   [150 137 133]
   [150 137 133]]

  [[174 160 153]
   [173 159 152]
   [172 158 151]
   ...
   [149 136 132]
   [149 136 132]
   [149 136 132]]

  [[173 159 152]
   [172 158 151]
   [171 157 150]
   ...
   [149 136 132]
   [149 136 132]
   [149 136 132]]]


 [[[ 87  78  75]
   [ 69  60  57]
   [ 89  80  77]
   ...
   [ 39  50  58]
   [ 35  46  54]
   [ 33  44  52]]

  [[ 87  78  75]
   [ 69  60  57]
   [ 89  80  77]
   ...
   [ 39  50  58]
   [ 35  46  54]
   [ 34  45  53]]

  [[ 89  80  77]
   [ 68  59  56]
   [ 88  79  76]
   ...
   [ 42  50  59]
   [ 40  4

(95, 270, 480, 3)
[[[[ 59  71  81]
   [ 59  71  81]
   [ 59  71  81]
   ...
   [180 188 210]
   [194 203 223]
   [192 201 221]]

  [[ 57  69  79]
   [ 57  69  79]
   [ 56  68  78]
   ...
   [184 192 214]
   [192 201 221]
   [193 202 222]]

  [[ 54  67  75]
   [ 54  67  75]
   [ 56  69  77]
   ...
   [178 186 208]
   [185 194 214]
   [184 193 213]]

  ...

  [[146 136 136]
   [146 136 136]
   [146 136 136]
   ...
   [152 141 138]
   [152 140 142]
   [152 140 142]]

  [[146 136 136]
   [146 136 136]
   [146 136 136]
   ...
   [153 142 139]
   [152 140 142]
   [152 140 142]]

  [[146 136 136]
   [146 136 136]
   [146 136 136]
   ...
   [153 142 139]
   [153 141 143]
   [153 141 143]]]


 [[[ 59  72  80]
   [ 59  72  80]
   [ 57  73  80]
   ...
   [170 181 196]
   [170 181 196]
   [170 181 196]]

  [[ 57  70  78]
   [ 57  70  78]
   [ 55  71  78]
   ...
   [174 185 200]
   [174 185 200]
   [174 185 200]]

  [[ 54  68  73]
   [ 56  70  75]
   [ 55  72  76]
   ...
   [179 190 205]
   [179 19

(22, 270, 480, 3)
[[[[ 65  78  94]
   [ 65  78  94]
   [ 65  78  94]
   ...
   [131 139 163]
   [132 140 164]
   [146 154 178]]

  [[ 65  78  94]
   [ 65  78  94]
   [ 65  78  94]
   ...
   [159 167 191]
   [163 171 195]
   [175 183 207]]

  [[ 63  76  92]
   [ 63  76  92]
   [ 63  76  92]
   ...
   [177 185 209]
   [181 189 213]
   [188 196 220]]

  ...

  [[141 132 136]
   [141 132 136]
   [141 132 136]
   ...
   [145 135 135]
   [143 135 135]
   [143 135 135]]

  [[141 132 136]
   [141 132 136]
   [141 132 136]
   ...
   [146 136 136]
   [144 136 136]
   [144 136 136]]

  [[141 132 136]
   [141 132 136]
   [141 132 136]
   ...
   [147 137 137]
   [145 137 137]
   [144 136 136]]]


 [[[ 65  78  94]
   [ 65  78  94]
   [ 65  78  94]
   ...
   [134 142 166]
   [139 147 171]
   [153 161 185]]

  [[ 65  78  94]
   [ 65  78  94]
   [ 65  78  94]
   ...
   [158 166 190]
   [164 172 196]
   [177 185 209]]

  [[ 63  76  92]
   [ 63  76  92]
   [ 63  76  92]
   ...
   [178 186 210]
   [184 19

(62, 270, 480, 3)
[[[[162 159 160]
   [212 209 210]
   [224 221 222]
   ...
   [ 67  67  79]
   [ 63  63  75]
   [ 60  60  72]]

  [[126 123 124]
   [141 138 139]
   [156 153 154]
   ...
   [ 67  67  79]
   [ 64  64  76]
   [ 61  61  73]]

  [[116 116 116]
   [111 111 111]
   [109 109 109]
   ...
   [ 68  68  80]
   [ 66  66  78]
   [ 62  62  74]]

  ...

  [[ 64  59  65]
   [ 71  66  72]
   [ 63  56  62]
   ...
   [ 97  83  95]
   [ 97  83  95]
   [ 97  83  95]]

  [[ 63  58  64]
   [ 53  48  54]
   [ 50  43  49]
   ...
   [ 97  83  95]
   [ 97  83  95]
   [ 97  83  95]]

  [[ 29  24  30]
   [ 33  28  34]
   [ 55  48  54]
   ...
   [ 97  83  95]
   [ 97  83  95]
   [ 97  83  95]]]


 [[[111 111 111]
   [109 109 109]
   [112 112 112]
   ...
   [ 56  56  68]
   [ 57  57  69]
   [ 60  60  72]]

  [[112 112 112]
   [112 112 112]
   [114 114 114]
   ...
   [ 57  57  69]
   [ 57  57  69]
   [ 60  60  72]]

  [[108 111 111]
   [107 110 110]
   [107 110 110]
   ...
   [ 59  59  71]
   [ 57  5

(366, 270, 480, 3)
[[[[ 97  93  83]
   [ 94  90  80]
   [ 92  88  78]
   ...
   [129 171 181]
   [130 172 182]
   [131 173 183]]

  [[ 97  93  83]
   [ 94  90  80]
   [ 92  88  78]
   ...
   [126 168 178]
   [127 169 179]
   [127 169 179]]

  [[ 97  93  83]
   [ 95  91  81]
   [ 92  88  78]
   ...
   [123 165 175]
   [123 165 175]
   [123 165 175]]

  ...

  [[159 147 140]
   [161 149 142]
   [162 150 143]
   ...
   [165 154 145]
   [165 154 145]
   [164 153 144]]

  [[164 152 145]
   [165 153 146]
   [166 154 147]
   ...
   [165 154 145]
   [165 154 145]
   [165 154 145]]

  [[169 157 150]
   [170 158 151]
   [171 159 152]
   ...
   [166 155 146]
   [166 155 146]
   [165 154 145]]]


 [[[104 103  83]
   [106 105  85]
   [108 104  87]
   ...
   [ 60  79  88]
   [ 60  79  88]
   [ 60  79  88]]

  [[104 103  83]
   [104 103  83]
   [108 104  87]
   ...
   [ 61  80  89]
   [ 61  80  89]
   [ 61  80  89]]

  [[106 105  85]
   [106 105  85]
   [108 105  85]
   ...
   [ 62  81  90]
   [ 62  

(113, 270, 480, 3)
[[[[  9   9   9]
   [  9   9   9]
   [  9   9   9]
   ...
   [ 23  28  34]
   [ 25  27  34]
   [ 24  26  33]]

  [[  9   9   9]
   [  9   9   9]
   [  9   9   9]
   ...
   [ 25  30  36]
   [ 27  29  36]
   [ 26  28  35]]

  [[  9   9   9]
   [  9   9   9]
   [  9   9   9]
   ...
   [ 25  30  36]
   [ 28  30  37]
   [ 28  30  37]]

  ...

  [[ 66  59  65]
   [ 66  59  65]
   [ 66  59  65]
   ...
   [ 61  54  65]
   [ 63  56  67]
   [ 63  56  67]]

  [[ 65  58  64]
   [ 65  58  64]
   [ 65  58  64]
   ...
   [ 61  54  65]
   [ 63  56  67]
   [ 63  56  67]]

  [[ 65  58  64]
   [ 65  58  64]
   [ 65  58  64]
   ...
   [ 61  54  65]
   [ 63  56  67]
   [ 63  56  67]]]


 [[[  9   9   9]
   [  9   9   9]
   [  9   9   9]
   ...
   [ 23  28  34]
   [ 25  27  34]
   [ 24  26  33]]

  [[  9   9   9]
   [  9   9   9]
   [  9   9   9]
   ...
   [ 23  28  34]
   [ 25  27  34]
   [ 24  26  33]]

  [[  9   9   9]
   [  9   9   9]
   [  9   9   9]
   ...
   [ 25  30  36]
   [ 27  

(666, 270, 480, 3)
[[[[ 42  55  71]
   [ 42  55  71]
   [ 42  55  71]
   ...
   [ 11  15  17]
   [ 11  15  17]
   [ 10  14  16]]

  [[ 42  55  71]
   [ 42  55  71]
   [ 42  55  71]
   ...
   [ 10  14  16]
   [ 10  14  16]
   [ 10  14  16]]

  [[ 42  55  71]
   [ 42  55  71]
   [ 42  55  71]
   ...
   [ 10  14  16]
   [ 10  14  16]
   [  8  12  14]]

  ...

  [[ 40  50  67]
   [ 40  50  67]
   [ 40  50  67]
   ...
   [ 79  71  71]
   [ 79  71  71]
   [ 79  71  71]]

  [[ 40  50  67]
   [ 40  50  67]
   [ 40  50  67]
   ...
   [ 79  71  71]
   [ 79  71  71]
   [ 79  71  71]]

  [[ 40  50  67]
   [ 40  50  67]
   [ 40  50  67]
   ...
   [ 79  71  71]
   [ 79  71  71]
   [ 79  71  71]]]


 [[[ 42  50  67]
   [ 42  50  67]
   [ 41  49  66]
   ...
   [ 12  16  18]
   [ 12  16  18]
   [ 11  15  17]]

  [[ 42  50  67]
   [ 42  50  67]
   [ 41  49  66]
   ...
   [ 11  15  17]
   [ 11  15  17]
   [ 10  14  16]]

  [[ 41  49  66]
   [ 41  49  66]
   [ 41  49  66]
   ...
   [ 10  14  16]
   [ 10  

(335, 270, 480, 3)
[[[[ 74  28  81]
   [ 75  29  82]
   [ 75  29  82]
   ...
   [110 118 122]
   [110 118 122]
   [110 118 122]]

  [[ 74  28  81]
   [ 75  29  82]
   [ 75  29  82]
   ...
   [110 118 122]
   [110 118 122]
   [110 118 122]]

  [[ 74  28  81]
   [ 75  29  82]
   [ 75  29  82]
   ...
   [110 118 122]
   [110 118 122]
   [110 118 122]]

  ...

  [[ 94  62 108]
   [ 94  62 108]
   [ 94  62 108]
   ...
   [140 136 139]
   [140 136 139]
   [140 136 139]]

  [[ 94  62 108]
   [ 94  62 108]
   [ 93  61 107]
   ...
   [140 136 139]
   [140 136 139]
   [140 136 139]]

  [[ 94  62 108]
   [ 94  62 108]
   [ 92  60 106]
   ...
   [140 136 139]
   [140 136 139]
   [140 136 139]]]


 [[[ 68  27  79]
   [ 68  27  79]
   [ 68  27  79]
   ...
   [109  89 104]
   [109  89 104]
   [109  89 104]]

  [[ 68  27  79]
   [ 68  27  79]
   [ 68  27  79]
   ...
   [109  89 104]
   [109  89 104]
   [109  89 104]]

  [[ 68  27  79]
   [ 68  27  79]
   [ 68  27  79]
   ...
   [109  89 104]
   [109  

(8, 270, 480, 3)
[[[[ 26  29  29]
   [ 28  31  31]
   [ 28  31  29]
   ...
   [ 51  54  52]
   [ 38  41  39]
   [ 29  32  30]]

  [[ 27  30  30]
   [ 28  31  31]
   [ 27  30  28]
   ...
   [ 52  55  53]
   [ 40  43  41]
   [ 30  33  31]]

  [[ 28  31  31]
   [ 28  31  31]
   [ 28  31  29]
   ...
   [ 50  53  51]
   [ 40  43  41]
   [ 30  33  31]]

  ...

  [[167 164 171]
   [167 164 171]
   [167 165 170]
   ...
   [ 99  95  98]
   [ 99  95  98]
   [ 99  95  98]]

  [[173 170 177]
   [173 170 177]
   [172 170 175]
   ...
   [102  98 101]
   [102  98 101]
   [102  98 101]]

  [[173 170 177]
   [173 170 177]
   [172 170 175]
   ...
   [105 101 104]
   [105 101 104]
   [105 101 104]]]


 [[[ 26  29  29]
   [ 27  30  30]
   [ 29  32  30]
   ...
   [ 54  57  55]
   [ 49  52  50]
   [ 41  44  42]]

  [[ 27  30  30]
   [ 28  31  31]
   [ 28  31  29]
   ...
   [ 55  58  56]
   [ 50  53  51]
   [ 42  45  43]]

  [[ 28  31  31]
   [ 28  31  31]
   [ 28  31  29]
   ...
   [ 54  57  55]
   [ 50  53

(531, 270, 480, 3)
[[[[ 40  47  58]
   [ 40  47  58]
   [ 40  47  58]
   ...
   [ 57  70  91]
   [ 57  70  91]
   [ 59  72  93]]

  [[ 40  47  58]
   [ 40  47  58]
   [ 40  47  58]
   ...
   [ 55  68  89]
   [ 55  68  89]
   [ 56  69  90]]

  [[ 40  47  58]
   [ 40  47  58]
   [ 40  47  58]
   ...
   [ 52  63  84]
   [ 54  65  86]
   [ 55  66  87]]

  ...

  [[ 62  62  74]
   [ 63  63  75]
   [ 62  66  75]
   ...
   [ 47  54  55]
   [ 46  53  54]
   [ 46  53  54]]

  [[ 68  67  84]
   [ 69  68  85]
   [ 68  71  84]
   ...
   [ 47  54  55]
   [ 46  53  54]
   [ 46  53  54]]

  [[ 75  74  91]
   [ 76  75  92]
   [ 73  76  89]
   ...
   [ 47  54  55]
   [ 46  53  54]
   [ 46  53  54]]]


 [[[ 40  47  58]
   [ 40  47  58]
   [ 40  47  58]
   ...
   [ 64  78  92]
   [ 65  79  93]
   [ 65  79  93]]

  [[ 40  47  58]
   [ 40  47  58]
   [ 40  47  58]
   ...
   [ 61  75  89]
   [ 62  76  90]
   [ 62  76  90]]

  [[ 40  47  58]
   [ 40  47  58]
   [ 40  47  58]
   ...
   [ 59  70  85]
   [ 60  

(167, 270, 480, 3)
[[[[ 41  40  50]
   [ 56  55  65]
   [ 64  63  73]
   ...
   [ 21  23  25]
   [ 21  23  25]
   [ 20  22  24]]

  [[ 43  42  52]
   [ 44  43  53]
   [ 54  53  63]
   ...
   [ 20  22  24]
   [ 21  23  25]
   [ 20  22  24]]

  [[ 43  42  52]
   [ 42  41  51]
   [ 48  47  57]
   ...
   [ 20  22  24]
   [ 20  22  24]
   [ 19  21  23]]

  ...

  [[ 66  54  66]
   [ 66  54  66]
   [ 66  54  66]
   ...
   [ 91  78  82]
   [ 90  77  81]
   [ 89  76  80]]

  [[ 67  55  67]
   [ 67  55  67]
   [ 67  55  67]
   ...
   [ 91  78  82]
   [ 89  76  80]
   [ 88  75  79]]

  [[ 67  55  67]
   [ 67  55  67]
   [ 67  55  67]
   ...
   [ 91  78  82]
   [ 88  75  79]
   [ 86  73  77]]]


 [[[ 41  40  50]
   [ 56  55  65]
   [ 64  63  73]
   ...
   [ 21  23  25]
   [ 21  23  25]
   [ 20  22  24]]

  [[ 43  42  52]
   [ 44  43  53]
   [ 54  53  63]
   ...
   [ 20  22  24]
   [ 21  23  25]
   [ 20  22  24]]

  [[ 43  42  52]
   [ 42  41  51]
   [ 48  47  57]
   ...
   [ 20  22  24]
   [ 20  

(302, 270, 480, 3)
[[[[ 72  77  83]
   [ 72  77  83]
   [ 72  77  83]
   ...
   [ 33  35  37]
   [ 33  35  37]
   [ 33  35  37]]

  [[ 72  77  83]
   [ 72  77  83]
   [ 72  77  83]
   ...
   [ 31  33  35]
   [ 31  33  35]
   [ 31  33  35]]

  [[ 72  77  83]
   [ 72  77  83]
   [ 72  77  83]
   ...
   [ 37  39  41]
   [ 37  39  41]
   [ 37  39  41]]

  ...

  [[144 139 151]
   [145 140 152]
   [142 140 152]
   ...
   [132 133 138]
   [130 131 136]
   [129 130 135]]

  [[144 139 151]
   [144 139 151]
   [141 139 151]
   ...
   [127 130 135]
   [125 128 133]
   [125 128 133]]

  [[143 138 150]
   [143 138 150]
   [139 137 149]
   ...
   [125 128 133]
   [123 126 131]
   [123 126 131]]]


 [[[ 72  77  83]
   [ 72  77  83]
   [ 72  77  83]
   ...
   [ 33  35  37]
   [ 33  35  37]
   [ 33  35  37]]

  [[ 72  77  83]
   [ 72  77  83]
   [ 72  77  83]
   ...
   [ 31  33  35]
   [ 31  33  35]
   [ 31  33  35]]

  [[ 72  77  83]
   [ 72  77  83]
   [ 72  77  83]
   ...
   [ 37  39  41]
   [ 37  

(321, 270, 480, 3)
[[[[109  99 112]
   [111 101 114]
   [113 103 116]
   ...
   [ 54  57  62]
   [ 54  57  62]
   [ 54  57  62]]

  [[113 103 116]
   [113 103 116]
   [113 103 116]
   ...
   [ 54  57  62]
   [ 54  57  62]
   [ 54  57  62]]

  [[116 106 119]
   [116 106 119]
   [116 106 119]
   ...
   [ 54  57  62]
   [ 54  57  62]
   [ 54  57  62]]

  ...

  [[ 31  17  29]
   [ 34  20  32]
   [ 37  23  35]
   ...
   [ 49  46  47]
   [ 47  44  45]
   [ 47  44  45]]

  [[ 28  14  26]
   [ 32  18  30]
   [ 32  18  30]
   ...
   [ 52  49  50]
   [ 52  49  50]
   [ 50  47  48]]

  [[ 32  18  30]
   [ 32  18  30]
   [ 32  18  30]
   ...
   [ 54  51  52]
   [ 53  50  51]
   [ 53  50  51]]]


 [[[103  96 107]
   [103  96 107]
   [105  98 109]
   ...
   [ 42  45  50]
   [ 42  45  50]
   [ 42  45  50]]

  [[106  99 110]
   [107 100 111]
   [107 100 111]
   ...
   [ 42  45  50]
   [ 42  45  50]
   [ 42  45  50]]

  [[112 105 116]
   [111 104 115]
   [111 104 115]
   ...
   [ 42  45  50]
   [ 42  

array([<src.Segment.Segment object at 0x7f79c836e7b8>,
       <src.Segment.Segment object at 0x7f79c839da90>], dtype=object)

'a'